# Generated by Django 2.2.28 on 2023-07-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilhetesSeatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateField(blank=True, db_column='CallDate', null=True)),
                ('calltime', models.TimeField(blank=True, db_column='CallTime', null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('extension', models.TextField(blank=True, null=True)),
                ('dialednumber', models.TextField(blank=True, null=True)),
                ('billedtime', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Bilhetes_SeaTIC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(blank=True, null=True)),
                ('calldate', models.DateField(blank=True, null=True)),
                ('calltime', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('extension', models.TextField(blank=True, null=True)),
                ('dialednumber', models.TextField(blank=True, null=True)),
                ('billedtime', models.DurationField(blank=True, null=True)),
                ('billedamount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'BillCenter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('secretaria', models.TextField(db_column='Secretaria')),
                ('ramal', models.TextField(db_column='Ramal', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostEvolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(blank=True, null=True)),
                ('nramais', models.IntegerField(blank=True, null=True)),
                ('total_ramal', models.IntegerField(blank=True, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('mcusto', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('tmcusto', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('monthyyyy', models.DateField(blank=True, db_column='MonthYYYY', null=True)),
            ],
            options={
                'db_table': 'Cost_Evolution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdEndpointtype',
            fields=[
                ('endpointtype', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'md_endpointtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdLogginghost',
            fields=[
                ('hostid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('limnumber', models.SmallIntegerField()),
                ('hostname', models.CharField(max_length=255)),
                ('exchangeid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'md_logginghost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdPhonecall',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('stopdate', models.DateField()),
                ('stoptime', models.TimeField()),
                ('duration', models.IntegerField()),
                ('dialednumber', models.CharField(max_length=40)),
                ('connectednumber', models.CharField(max_length=40)),
                ('conditioncode', models.SmallIntegerField()),
                ('callcasedata', models.IntegerField()),
                ('chargednumber', models.CharField(max_length=40)),
                ('seqnumber', models.IntegerField()),
                ('seqlim', models.SmallIntegerField()),
                ('callid', models.CharField(max_length=24)),
                ('callidass1', models.CharField(max_length=24)),
                ('callidass2', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'md_phonecall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PbxProcessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('extension', models.TextField(blank=True, null=True)),
                ('dialednumber', models.TextField(blank=True, null=True)),
                ('connectednumber', models.TextField(blank=True, null=True)),
                ('conditioncode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PBX Processed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('qtdminutes', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costcharged', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('qtdcall', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ReportSummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValoresSeatic',
            fields=[
                ('tipo_de_ligacao', models.TextField(db_column='Tipo de Ligacao', primary_key=True, serialize=False)),
                ('valor', models.FloatField(blank=True, db_column='Valor', null=True)),
                ('tam', models.FloatField(blank=True, db_column='TAM', null=True)),
                ('val1', models.FloatField(blank=True, db_column='Val1', null=True)),
                ('cmb', models.FloatField(blank=True, db_column='CMB', null=True)),
                ('preco_etice_nuvem', models.FloatField(blank=True, db_column='PRECO_ETICE_NUVEM', null=True)),
            ],
            options={
                'db_table': 'Valores_SeaTIC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeaccount',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('accountcode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'md_chargeaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargecil',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('cilcode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'md_chargecil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargedata',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('accesscode1', models.CharField(max_length=10)),
                ('accesscode2', models.CharField(max_length=10)),
                ('cstcorrdata', models.CharField(max_length=20)),
                ('eventlevel', models.SmallIntegerField()),
                ('ismobilelogging', models.BooleanField()),
            ],
            options={
                'db_table': 'md_chargedata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeequ',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('lim', models.SmallIntegerField()),
                ('magazine', models.SmallIntegerField()),
                ('board', models.SmallIntegerField()),
                ('individual', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_chargeequ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeexttime',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('ringtimecounter', models.SmallIntegerField()),
                ('queuetimecounter', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_chargeexttime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeinctrunk',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('inctrnkid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'md_chargeinctrunk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeogtrunk',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('ogtrnkid', models.CharField(max_length=10)),
                ('trnkquetim', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_chargeogtrunk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeopqueue',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('opquetim', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_chargeopqueue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargeosa',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('osacode', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'md_chargeosa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargepulses',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('taxpulses', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_chargepulses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdChargetns',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('tnscode', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'md_chargetns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdPhonecallcallingnumber',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('callingnumber', models.CharField(max_length=40)),
                ('callingnumbertype', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_phonecallcallingnumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdQualityaddress',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('endpoint', models.SmallIntegerField()),
                ('rtpaddress', models.CharField(max_length=54)),
                ('extension', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'md_qualityaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdQualitydata',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('endpoint', models.SmallIntegerField()),
                ('worstestimatedendtoenddelay', models.IntegerField()),
                ('meanestimatedendtoenddelay', models.IntegerField()),
                ('cumnumpacketslost', models.IntegerField()),
                ('packetlostrate', models.SmallIntegerField()),
                ('worstjitter', models.IntegerField()),
                ('estimatedthroughput', models.IntegerField()),
                ('fractionlostrate', models.SmallIntegerField()),
                ('meanjitter', models.IntegerField()),
                ('simplervalue', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'md_qualitydata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdQualitydatacodec',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='voip.MdPhonecall')),
                ('endpoint', models.SmallIntegerField()),
                ('typeofcodec', models.CharField(max_length=1)),
                ('codec', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'md_qualitydatacodec',
                'managed': False,
            },
        ),
    ]
