SOLICITATION_OPENED = 1
SOLICITATION_APPROVED = 2
SOLICITATION_CANCELED = 3
SOLICITATION_DENIED = 4

SOLICITATION_STATUS_CHOICES = [
    (SOLICITATION_OPENED,   'Aberto'),
    (SOLICITATION_APPROVED, 'Aprovado'),
    (SOLICITATION_CANCELED, 'Cancelado'),
    (SOLICITATION_DENIED,   'Negado')
]
