# Generated by Django 5.0.1 on 2025-01-04 15:09

import django_extensions.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Configuração da Organização',
                'verbose_name_plural': 'Configurações da Organização',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
