# Generated by Django 5.0.1 on 2024-01-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('phonecalls', '0003_price_othertype_alter_pricetable_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='other_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_orgsettings_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores Serviços Diversos'),
        ),
    ]
