# Generated by Django 5.0.1 on 2025-01-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('phonecalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='call_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_orgsettings_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores Serviços de Comunicação'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='other_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_orgsettings_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores Serviços Diversos'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='service_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orgsettings_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores Serviços Básicos'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
