# Generated by Django 5.0.1 on 2025-01-04 15:09

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extension_range', models.CharField(max_length=100, verbose_name='Faixa de Ramais')),
            ],
            options={
                'verbose_name': 'Faixa de ramal atribuido ao sistema',
                'verbose_name_plural': 'Faixa de ramais atribuidos ao sistema',
            },
        ),
        migrations.CreateModel(
            name='ExtensionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extension', models.CharField(max_length=50, unique=True, verbose_name='Ramal')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.center', verbose_name='Centro de Custo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.company', verbose_name='Empresa')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Organização')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Ramal',
                'verbose_name_plural': 'Ramais',
            },
        ),
        migrations.CreateModel(
            name='ExtensionSolicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extension_range', models.CharField(max_length=600, verbose_name='Faixa de Ramais')),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Aprovado'), (3, 'Cancelado'), (4, 'Negado')], default=1, verbose_name='Status da Solicitação')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.company', verbose_name='Empresa')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Solicitação de Ramais',
                'verbose_name_plural': 'Solicitações de Ramais',
            },
        ),
    ]
