# Generated by Django 2.2.28 on 2023-07-20 14:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('extensions', '0001_initial'),
        ('organizations', '0003_field_fix_and_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('servicetype', models.IntegerField(choices=[(1, 'Serviços Básicos de Disponibilidade e Contact Center'), (2, 'Serviços de Comunicação')], verbose_name='Tipo de Serviço')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Tabela de Valores',
                'verbose_name_plural': 'Tabelas de Valores',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('calltype', models.IntegerField(blank=True, choices=[(1, 'Ligações para celular local (VC1)'), (2, 'Ligações para celular na mesma região (VC2)'), (3, 'Ligações para celular em outra área (VC3)'), (4, 'Ligações locais para fixo'), (5, 'Ligações DDD para fixo'), (6, 'Ligação internacional'), (7, 'Grátis'), (8, 'Desconhecido'), (9, 'AddedValue')], null=True, verbose_name='Tipo de Chamada')),
                ('basic_service', models.IntegerField(blank=True, choices=[(1, 'Serviço de Acesso Nivel 1'), (2, 'Serviço de Acesso Nivel 2'), (3, 'Serviço de Acesso Nivel 3'), (4, 'Serviço de Acesso Nivel 4'), (5, 'Serviço de Acesso Nivel 5'), (6, 'Serviço de Acesso Nivel 6'), (7, 'Serviço de Acesso sem fio'), (8, 'Serviço de acesso via Software'), (9, 'Serviço de Extensão via software'), (10, 'Gerência e Operação da Plataforma Básica de Contact Center'), (11, 'Gerência e Operação da Plataforma Básica de Gravação'), (12, 'Gerência e Operação de Posição de Atendimentos'), (13, 'Gerência e Operação de Supervisor'), (14, 'Gerência e Operação de Acompanhamento em Tempo Real'), (15, 'Gerência e Operação de Canal de Atendimento Automático e Mensagens'), (16, 'Gerência e Operação de Posição de Gravação'), (17, 'Gerência e Operação de Supervisor de Gravação')], null=True, verbose_name='Tipo de Serviço Básico')),
                ('basic_service_amount', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Serviço Básico')),
                ('value', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Preço')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonecalls.PriceTable', verbose_name='Tabela de Valores')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
        migrations.CreateModel(
            name='Phonecall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pabx', models.IntegerField(choices=[(1, 'Chamada recebida'), (2, 'Chamada recebida abandonada'), (3, 'Chamada externa'), (4, 'Chamada externa abandonada'), (5, 'Chamada interna'), (6, 'Chamada interna abandonada'), (7, 'Conferência'), (8, 'Chamada transferida'), (9, 'Número ocupado'), (10, 'Número não existe'), (11, 'Não classificado')], db_index=True, verbose_name='Classificação PABX')),
                ('inbound', models.BooleanField(db_index=True, default=True, verbose_name='Chamada Entrante')),
                ('internal', models.BooleanField(db_index=True, default=False, verbose_name='Chamada Interna')),
                ('calltype', models.IntegerField(choices=[(1, 'Ligações para celular local (VC1)'), (2, 'Ligações para celular na mesma região (VC2)'), (3, 'Ligações para celular em outra área (VC3)'), (4, 'Ligações locais para fixo'), (5, 'Ligações DDD para fixo'), (6, 'Ligação internacional'), (7, 'Grátis'), (8, 'Desconhecido'), (9, 'AddedValue')], db_index=True, verbose_name='Tipo de Chamada')),
                ('service', models.IntegerField(blank=True, choices=[(1, 'Serviços Públicos de Emergência'), (2, 'Serviços de Utilidade Pública'), (3, 'Serviços de Apoio a Telefonia'), (4, 'Prestadoras de Telefonia Fixa'), (5, 'Prestadoras de Telefonia Celular'), (6, 'Prestadoras de TV por Assinatura'), (7, 'Outro Serviço'), (8, 'Serviço Desconhecido')], db_index=True, null=True, verbose_name='Serviço')),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=20, verbose_name='Preço')),
                ('org_price', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=20, verbose_name='Preço para Organização')),
                ('billedamount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=20, verbose_name='Valor Faturado')),
                ('org_billedamount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=20, verbose_name='Valor Faturado para Organização')),
                ('billedtime', models.IntegerField(verbose_name='Tempo Faturado')),
                ('md_phonecall_id', models.IntegerField(blank=True, null=True)),
                ('startdate', models.DateField(verbose_name='Data de Início')),
                ('starttime', models.TimeField(verbose_name='Hora de Início')),
                ('stopdate', models.DateField(verbose_name='Data de Encerramento')),
                ('stoptime', models.TimeField(verbose_name='Hora de Encerramento')),
                ('duration', models.IntegerField(verbose_name='Duração')),
                ('chargednumber', models.CharField(max_length=40, verbose_name='Número Cobrado')),
                ('connectednumber', models.CharField(max_length=40, verbose_name='Número Conectado')),
                ('dialednumber', models.CharField(max_length=40, verbose_name='Número Discado')),
                ('conditioncode', models.SmallIntegerField(verbose_name='Código de Condição')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.Center', verbose_name='Centro de Custo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.Company', verbose_name='Empresa')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extensions.ExtensionLine', verbose_name='Ramal')),
                ('org_price_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_phonecalls', to='phonecalls.PriceTable', verbose_name='Tabela de Valores para Organização')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization', verbose_name='Organização')),
                ('price_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phonecalls', to='phonecalls.PriceTable', verbose_name='Tabela de Valores')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.Sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
                'ordering': ['-md_phonecall_id'],
            },
        ),
        migrations.AddIndex(
            model_name='phonecall',
            index=models.Index(fields=['-startdate'], name='phonecalls_date_idx'),
        ),
    ]
