# Generated by Django 5.0.1 on 2024-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0002_alter_phonecall_id_alter_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='othertype',
            field=models.IntegerField(blank=True, choices=[(1, 'Serviços especializados de comunicação VoIP por demanda '), (2, 'Serviço de deslocamento para prestar serviço fora da Região Metropolitana de Fortaleza')], null=True, verbose_name='Tipo de Serviço Diverso'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='servicetype',
            field=models.IntegerField(choices=[(1, 'Serviços Básicos de Disponibilidade e Contact Center'), (2, 'Serviços de Comunicação'), (3, 'Serviços Diversos')], verbose_name='Tipo de Serviço'),
        ),
    ]
