# Generated by Django 5.0.1 on 2024-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0003_price_othertype_alter_pricetable_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='basic_service',
            field=models.IntegerField(blank=True, choices=[(1, 'Serviço de Acesso VoIP com aparelho 2 SIP e 100 Mb'), (2, 'Serviço de Acesso VoIP com aparelho 2 SIP e 100 MbE PoE'), (3, 'Serviço de Acesso VoIP com aparelho 4 SIP, 1GbE e teclado função'), (4, 'Serviço de Acesso VoIP com aparelho 10 SIP, 1GbE e teclado função'), (5, 'Serviço de Acesso com aparelho sem fio com base 2 SIP, 100 MbE e DECT'), (6, 'Serviço de Acesso VoIP sem fio com aparelho 2 SIP sem fio WiFi'), (7, 'Serviço de Acesso VoIP sem aparelho (aparelho contratante)'), (8, 'Serviço de acesso via Software'), (9, 'Serviço de Extensão via software'), (10, 'Gerência e Operação da Plataforma Básica de Contact Center'), (11, 'Gerência e Operação da Plataforma Básica de Gravação'), (12, 'Gerência e Operação de Posição de Atendimentos'), (13, 'Gerência e Operação de Supervisor'), (14, 'Gerência e Operação de Acompanhamento em Tempo Real'), (15, 'Gerência e Operação de Canal de Atendimento Automático e Mensagens'), (16, 'Gerência e Operação de Posição de Gravação'), (17, 'Gerência e Operação de Supervisor de Gravação')], null=True, verbose_name='Tipo de Serviço Básico'),
        ),
    ]
