# Generated by Django 5.0.1 on 2024-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0004_alter_price_basic_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='basic_service',
            field=models.IntegerField(blank=True, choices=[(1, 'Serviço de Acesso Nivel 1'), (2, 'Serviço de Acesso Nivel 2'), (3, 'Serviço de Acesso Nivel 3'), (4, 'Serviço de Acesso Nivel 4'), (5, 'Serviço de Acesso Nivel 5'), (6, 'Serviço de Acesso Nivel 6'), (7, 'Serviço de Acesso sem fio'), (8, 'Serviço de acesso via Software'), (9, 'Serviço de Extensão via software'), (10, 'Gerência e Operação da Plataforma Básica de Contact Center'), (11, 'Gerência e Operação da Plataforma Básica de Gravação'), (12, 'Gerência e Operação de Posição de Atendimentos'), (13, 'Gerência e Operação de Supervisor'), (14, 'Gerência e Operação de Acompanhamento em Tempo Real'), (15, 'Gerência e Operação de Canal de Atendimento Automático e Mensagens'), (16, 'Gerência e Operação de Posição de Gravação'), (17, 'Gerência e Operação de Supervisor de Gravação')], null=True, verbose_name='Tipo de Serviço Básico'),
        ),
    ]
