# Generated by Django 5.0.1 on 2025-01-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0001_initial'),
        ('phonecalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractbasicservices',
            name='org_price_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_contract', to='phonecalls.pricetable', verbose_name='Tabela de Valores para Organização'),
        ),
    ]
