# Generated by Django 5.0.1 on 2025-01-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0002_contractbasicservices_org_price_table'),
        ('centers', '0002_initial'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Organização'),
        ),
    ]
