# Generated by Django 5.0.1 on 2025-01-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0003_equipment_company_equipment_organization'),
        ('centers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.center', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.sector', verbose_name='Setor'),
        ),
    ]
