# Generated by Django 5.0.1 on 2025-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0004_equipment_center_equipment_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofphone',
            name='servicetype',
        ),
        migrations.AddField(
            model_name='typeofphone',
            name='servicetype',
            field=models.ManyToManyField(blank=True, null=True, to='Equipments.contractbasicservices', verbose_name='Organização'),
        ),
    ]
