# Generated by Django 5.0.1 on 2025-01-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0005_remove_typeofphone_servicetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipments.contractbasicservices', verbose_name='Contrato'),
        ),
    ]
