# Generated by Django 5.0.1 on 2025-01-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0006_equipment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractbasicservices',
            name='is_subcontract',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
