# Generated by Django 5.0.1 on 2025-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipments', '0007_contractbasicservices_is_subcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractbasicservices',
            name='item_number',
            field=models.IntegerField(default=0, verbose_name='Item #'),
            preserve_default=False,
        ),
    ]
