# Generated by Django 5.0.1 on 2025-01-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('organizations', '0006_alter_organization_slug'),
        ('phonecalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='call_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_company_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores - Serviços de Comunicação'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_company_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores - Serviços Diversos'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores - Serviços Básicos'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='center',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(through='centers.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sector',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='sector',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='sector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organização'),
        ),
    ]
