# Generated by Django 2.2.28 on 2023-07-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers', '0001_initial'),
        ('phonecalls', '0001_initial'),
        ('organizations', '0003_field_fix_and_editable'),
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='call_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_company_set', to='phonecalls.PriceTable', verbose_name='Tabela de Valores - Serviços de Comunicação'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_set', to='phonecalls.PriceTable', verbose_name='Tabela de Valores - Serviços Básicos'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Region', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(through='centers.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='center',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Organização'),
        ),
    ]
