# Generated by Django 5.0.1 on 2024-01-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_center_id_alter_company_id_and_more'),
        ('phonecalls', '0003_price_othertype_alter_pricetable_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_pricetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_company_set', to='phonecalls.pricetable', verbose_name='Tabela de Valores - Serviços Diversos'),
        ),
    ]
