# Generated by Django 5.0.1 on 2024-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_company_other_pricetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_new_contract',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is new contract?'),
        ),
    ]
