# Generated by Django 5.0.1 on 2024-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_company_is_new_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_new_contract',
            field=models.IntegerField(choices=[(0, 'Contrato antigo'), (1, 'Contrato Novo')], default=0, verbose_name='Is new contract?'),
        ),
    ]
